<script setup>
import { onMounted, ref } from 'vue';
import { apiFetch, money } from '../../app/services/api';
const cart = ref({ items: [], totals: {} }); const error = ref('');
async function load() { try { const response = await apiFetch('/cart'); cart.value = response.data || {}; } catch (e) { error.value = e.message; } }
async function update(item, quantity) { await apiFetch('/cart/update', { method: 'PUT', body: JSON.stringify({ product_id: item.product_id || item.id, quantity: Math.max(0, quantity) }) }); await load(); }
onMounted(load);
</script>
<template><section class="content page-content"><div class="page-header"><h1>Your cart</h1><a class="btn-primary" href="index.html?view=legacy&page=choosedelivery">Checkout</a></div><p v-if="error" class="empty-state">{{ error }}</p><div v-else-if="!cart.items?.length" class="empty-cart">Your cart is empty. <a href="index.html">Start shopping</a></div><div v-else class="cart-layout"><div class="cart-items"><div v-for="item in cart.items" :key="item.product_id || item.id" class="cart-item"><div class="item-details"><h3 class="item-name">{{ item.name || item.product_name }}</h3><p class="item-vendor">{{ item.vendor_name || item.vendor }}</p><p class="item-price">{{ money(item.price) }}</p></div><div class="item-actions"><div class="quantity-control"><button class="qty-btn" type="button" @click="update(item, Number(item.quantity) - 1)">-</button><span>{{ item.quantity }}</span><button class="qty-btn" type="button" @click="update(item, Number(item.quantity) + 1)">+</button></div><button class="remove-item" type="button" @click="update(item, 0)">Remove</button></div></div></div><aside class="order-summary"><p>Subtotal <strong>{{ money(cart.totals?.subtotal || cart.subtotal) }}</strong></p><p>Delivery <strong>{{ money(cart.totals?.delivery_fee || cart.delivery_fee) }}</strong></p><p class="total">Total <strong>{{ money(cart.totals?.total || cart.total) }}</strong></p></aside></div></section></template>
